# Generated by Django 4.2.9 on 2024-03-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
    ]
