# Generated by Django 4.2.9 on 2024-03-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_character_date_of_birth_remove_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
