# Generated by Django 4.2.9 on 2024-05-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='character_avatar/'),
        ),
    ]
