# Generated by Django 4.2.9 on 2024-07-11 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_family_character_family_role_character_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='app.world'),
        ),
    ]
