# Generated by Django 4.2.9 on 2024-08-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_character_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='world',
            name='time_period',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
