# Generated by Django 4.2.9 on 2024-08-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_world_description_world_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
